---
title: "lab-methods"
output:
  pdf_document: default
  html_document: default
date: "2022-10-26"
---

<!-- This file was adapted from VISCtemplates {{pkg_ver}}. -->


# Lab Methods GTL

The qualified GranToxiLux Antibody-Dependent Cell-Mediated Cytotoxicity (GTL-ADCC) assay was performed as previously described *[1]*. Target cells were a clonal isolate of the CEM.NKRCCR5 CD4+ T-cell line (NIH AIDS Reagent Program, Division of AIDS, NIAID, NIH: from Dr. Alexandra Trkola *[2]*. These cells were  coated with recombinant gp120s representing the HIV-1 envelopes of the subtype [specify subtype and antigens, e.g. C (TV1 and 1086c)]. Effector cells were PBMCs obtained from a HIV-seronegative donor with heterozygous for Fc$\gamma$R3A at position 158 (158F/V). PBMCs were obtained by leukapheresis to collect enough cells for completion of the study with a single donation, minimizing potential effector cell population variability effects on the study outcome.  PBMCs were used at an effector cell to target cell ratio of 30:1. Serum samples were tested after five-fold serial dilutions starting at 1:50. Each plate has one standardized positive control in duplicate and one standardized negative control in duplicate. 

ADCC is quantified as net percent granzyme B activity, which is the percent of target cells positive for GTL (an indicator of granzyme B uptake) minus the percent of target cells positive for GTL when incubated with effector cells in the absence of a source of antibodies. Flow cytometry is used to quantify the frequency of granzyme B positive cells.

<!-- Pollara and Hart et al 2011 [1] -->
<!-- Trkola et al 1999 [2] -->


# Lab Methods Luciferase

We utilized a modified version of a previously published ADCC luciferase procedure *[1, 2]*. Briefly, CEM.NKRCCR5 cells *[3]* were used as targets for ADCC luciferase assays after infection by one of the following HIV-1 [vaccine-matched, if all IMCs are vaccine-matched; if not, indicate match in table below] IMCs:
Complete IMC name	Accession Number	Abbreviated name	Vaccine Match
[Full name, as uploaded by lab]	[provided by lab]	[SRA-derived abbreviated name shown in tables and figures]	[if a mix of matched and unmatched IMCs were tested, indicate here which were matched]

Peripheral blood mononuclear cells (PBMCs) were obtained from a HIV-seronegative donor by leukapheresis and cryopreserved until the day of the assay. After thawing and overnight resting in RPMI 1640 supplemented with antibiotics, $10\%$ fetal bovine serum (R10), and 10 ng/mL of IL-15, the PBMCs were used as effector cells at an effector-to-target ratio of 30:1. 

Target and effector cells were plated in white 96-well half-area plates and co-cultured with 4-fold serial dilutions of trial participant serum starting at the 1:50 dilution. For each sample, percent specific killing was measured in duplicate at dilutions of 1:50, 1:200, and 1:800, 1:3200, 1:12800, and 1:51200. Co-cultures were incubated for 6 hours at $37^{\circ}$C in $5\%$ CO2. The final readout was the reduction of luminescence intensity generated by the presence of residual intact target cells that had not been lysed by the effector population in the presence of ADCC-mediating serum antibodies. The percentage of killing was calculated using the formula: percent specific loss Luciferase activity = $100 * \frac{\text{RLU of target and effector well– RLU of test well)}}{\text{RLU of target and effector well}}$.

In this analysis, the Relative Luminescence Units (RLU) of the target plus effector wells represents spontaneous lysis in the absence of any source of antibody and is used to calculate background activity. The monoclonal antibody [insert antibody name from lab study plan, e.g. Synagis] and a cocktail of HIV-1 monoclonal antibodies [insert antibody names from lab study plan, e.g. (A32, 2G12, CH44, and 7B2)] were used as negative and positive controls, respectively. 

<!-- 1.	Pollara, Justin, Mattia Bonsignori, M. Anthony Moody, Pinghuang Liu, S. Munir Alam, Kwan-Ki Hwang, Thaddeus C. Gurley, et al . 2014. “HIV-1 Vaccine-Induced C1 and V2 Env-Specific Antibodies Synergize for Increased Antiviral Activities.” Journal of Virology 88, no. 14: 7715–7726. https://doi:10.1128/JVI.00156-14. -->

<!-- full author list for 1:  Justin Pollara, Mattia Bonsignori, M. Anthony Moody, Pinghuang Liu, S. Munir Alam, Kwan-Ki Hwang, Thaddeus C. Gurley, Daniel M. Kozink, Lawrence C. Armand, Dawn J. Marshall, John F. Whitesides, Jaranit Kaewkungwal, Sorachai Nitayaphan, Punnee Pitisuttithum, Supachai Rerks-Ngarm, Merlin L. Robb, Robert J. O'Connell, Jerome H. Kim, Nelson L. Michael, David C. Montefiori, Georgia D. Tomaras, Hua-Xin Liao, Barton F. Haynes, and Guido Ferrari -->

<!-- 2.	Fisher, L., Zinter, M., Stanfield-Oakley, S., Carpp, L.N., Edwards, R.W., Denny, T., Moodie, Z., Laher, F., Bekker, L.G., McElrath, M.J. and Gilbert, P.B., 2019. Vaccine-induced antibodies mediate higher antibody-dependent cellular cytotoxicity after interleukin-15 pretreatment of natural killer effector cells. Frontiers in immunology, 10, p.2741. -->


<!-- 3.	Trkola, Alexandra, Jamie Matthews, Cynthia Gordon, Tom Ketas, and John P. Moore. 1999. “A Cell Line Based Neutralization Assay for Primary Human Immunodeficiency Virus Type 1 Isolates That Use Either the CCR5 or the CXCR4 Coreceptor.” Journal of Virology 73, no. 11: 8966-8974. https://doi.org/10.1128/jvi.73.11.8966-8974.1999.  -->
