---
title: "Using a VISC Report Template"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using a VISC Report Template}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Getting started with a template

There are a few different types of reports available:

* **empty**: A blank report template that includes the VISC header, but no other text.
* **generic**: A PT report template that includes generic text that can be adapted to your statistical analysis.
* **bama**: A PT report template for the BAMA assay.
* **nab**: A PT report template for the NAb assay.

To use a VISC report template, run:

```{r eval=FALSE}
use_visc_report(
  report_name = "VDCnnn_BAMA_PT_Report_statusifapplicable", # the name of the report file
  path = "BAMA", # the path within the active directory, usually the name of the assay
  report_type = "bama" # "empty", "generic", "bama", or "nab"
)
```

If you choose any `report_type` other than `"empty"`, this will set 
up a specific structure in the directory specified in `path`. Continuing with the BAMA
example above, this structure looks like:

```
|- BAMA/
|  +- VDCnnn_BAMA_PT_Report_statusifapplicable/              
|     +- BAMA-PT-Report.Rmd             # VISC report template
|     +- methods/                       # folder with "child" .Rmd documents
|       +- biological-endpoints.Rmd
|       +- lab-methods.Rmd
|       +- statistical-methods.Rmd
```

The "child" R Markdown documents contain standardized language for the methods
sections of PT reports. 
Edit these as needed for the specifics of your analysis.

You can use a VISC report template through the RStudio GUI 
(`File > New File > Rmarkdown... > From Template`), 
or with `rmarkdown::draft()`,
but this does not automatically generate the "child" R Markdown documents, 
so you will have to do that manually or with `use_visc_methods()` if you choose this option.

## Knit to PDF or Word

The VISC report R Markdown template knits to either a PDF or Word document. 

* Use the Knit button select either the PDF (visc_pdf_document) or 
Word (visc_word_document) output.
* Note the shortcut Ctrl-Shift-K will run the first output in the YAML, will be the last output run (starts off as PDF first).
* If you want to run both reports in one command, either use `rmarkdown::render()` with `output_format = 'all'`, or install the loom package and create a RStudio Addin (<https://github.com/thebioengineer/loom>).


## Using the template 

There are some new functions and coding conventions that help with knitting the report to both outputs.

### Page breaks

* For page breaks use `\clearpage`.
    
### Referencing
`
**Figure and table references**

* For figure and table references use `insert_ref()` function.
    + For example: `` `r knitr::inline_expr("insert_ref('fig:response-rate-plot')")` ``.
* Make sure chunk names only use dashes or referring will not work (no spaces or underscores).
* Do not use figure or table labels in chunk headings or kable code (e.g., don't use `fig.cap = "My Figure Caption \\label{my_figure_label}"`. Rmarkdown will automatically assign the chunk name as the figure/table reference label.

**Sections** 

* For referencing sections, use `insert_ref()` but you must list both the section label and the desired section name
    + For example: `` `r knitr::inline_expr("insert_ref('referencing', 'Referencing')")` `` gives `r VISCtemplates::insert_ref('referencing', 'Referencing')`.
    + For example: `` `r knitr::inline_expr("insert_ref('page-breaks', 'Page breaks')")` `` gives `r VISCtemplates::insert_ref('page-breaks', 'Page breaks')`.
* For PDF output the matching section number is display regardless of the section name listed.
* For Word output the section name listed is displayed.

**References/Bibliography**

*  For referencing papers inline, simply use the @ symbol before bib file reference (e.g., "As specified in `@Huang:2013fl`, ...").
*  For referencing papers in parentheses at the end of a sentence, use brackets and the @ symbol (e.g., `[@Huang:2013fl]`). The parentheses will be automatically included - do not add any extra.
*  For multiple papers in the same citation, separate with a semicolon (e.g., ` [@Suissa1985; @Lyderson2009]`).

### Tables

* Only output one table per code chunk.
* Make sure to have `format = output_type` in the `kableExtra::kable()` call 
    + `output_type` is either "latex" or "pandoc" depending on current report output.
* The table name will be chunk name plus "tab:".
    + For example, if chunk name is "descriptive-stats" then the table label will be "tab:descriptive-stats"
* Note that Word output cannot support many kableExtra features, such as `kableExtra::kable_styling()`.
   + Set `warning=kable_warnings` chunk option, otherwise Word output will have unwanted warnings.

### Figures

* Only output one figure per code chunk.
* Figure name will be chunk name plus "fig:".
    + i.e. if chunk name is "my-boxplot" then the table label will be "fig:my-boxplot".
    
### P values

* When using `VISCfunctions::pretty_pvalues()` make sure to use `output_type = output_type`,  `bold  = pandoc_markup`, and `italic = pandoc_markup`. This will give the appropriate markup depending on PDF or Word output.

### Sourcing external R scripts

* When using the `source()` function for external R scripts, use its `local = TRUE` argument. This will ensure that the objects created are placed in your Rmd's environment, rather than your global environment, which is a safer practice.

### Loading external data

* When using the `data()` function to load external data (e.g. from another package), specify `environment = environment()`. This will ensure that the object is placed in your Rmd's environment, rather than your global environment, which is a safer practice. See the "Good practice" section in `?utils::data` for more info.
