---
title: "{{ study_name}} Biological Endpoints"
output: github_document
---

<!-- The markdown (*.md) file is generated from the R Markdown (*.Rmd) file.
Please edit the *.Rmd file. -->

<!-- this file was adapted from VISCtemplates {{pkg_ver}}. -->

Serum [IgG/IgA] responses were measured against 
[# antigens; list antigens or reference antigen summary table at end of sentence]
using the binding antibody multiplex assay (BAMA). 
Antibody levels were measured as median fluorescent intensity (MFI) from two 
wells and then averaged using the mean. 
Background adjustment was applied using MFI measured from wells with beads that 
include buffer instead of sample. 
Additionally, a blank or reference bead was included to estimate non-specific 
antibody binding. 
Results were obtained for 
[a single dilution at 1:80 for animal data, 1:50 for human data; can vary]. 

<!-- For differential binding antigens only -->

The set includes antigens which highlight regions of differential binding to 
[insert target, e.g., the CD4 binding site of the HIV-1 envelope]. 
The differential binding set is comprised of [#] experimental 
[if applicable, (including the vaccine-matched antigen [insert vaccine-matched antigen])] and 
[#] matched reference antigens, where the reference antigens lack accessible 
target binding sites (knockout sites) present in the experimental antigens [reference tables]. 
[If applicable] An abbreviated name is used to simplify figures and tables 
included in this report and is proposed for each antigen [reference table].

<!-- Either in an antigen summary table or in the biological endpoints section, 
include information on antigen clade, any relevant panel information 
(e.g., antigen reagent project [ARP], see https://pubmed.ncbi.nlm.nih.gov/29386288/),
sample size by antigen, positivity threshold, and whether a blank or a reference 
bead was used. For differential binding antigens, include a table of the 
experimental and paired reference antigens, abbreviated antigen names if used, 
and the target site for antibody binding. -->

## BAMA Avidity

[Antigen and/or isotype specific] binding antibody responses were measured on a Bio-Plex 
(Bio-Rad) instrument (Bio-Plex 200 or Bio-Plex FM3D) using a standardized custom Luminex based assay.
Antigen specific antibody responses were measured at the following dilutions: [dilution (antigen/isotype) 
listed] and titrated [x-fold].

<-- add reference -->
<-- Tomaras, G. D. et al. Vaccine-induced plasma IgA specific for the C1 region of the HIV-1 envelope blocks binding and effector function of IgG. Proceedings of the National Academy of Sciences of the United States of America 110, 9019–9024 (2013). -->

Briefly, antigens were bound to carboxylated fluorescent microspheres (MagPlex, Luminex). Antigen bound 
microspheres were then incubated with human sera, along with standards and controls, for 30 minutes at 
750 RPM and 22°C. Mouse anti-human IgG1 (BioLegend, clone 12G8G11) and Mouse anti-human IgG3 (BioLegend, 
clone HP6047) followed by Goat Anti-Mouse IgG PE (Biolegend, catalog 405307) were used to detect IgG1 
and IgG3 antibody responses. Assay plates were read on the Bio-Plex 200 or Bio-Plex FM3D (Bio-Rad) 
system providing a readout of background subtracted mean fluorescence intensity (MFI).

All samples, controls and standards were assayed in duplicate; negative controls and uncoupled microspheres 
were included in each assay to ensure binding specificity. Positive and negative controls were included in 
each assay to ensure assay consistency and reproducibility. Levey-Jennings charts were also utilized to track 
antigen performance throughout the study.

