---
title: "Statistical Methods"
output: github_document
---

<!-- The markdown (*.md) file is generated from the R Markdown (*.Rmd) file.
Please edit the *.Rmd file. -->

<!-- this file was adapted from VISCtemplates {{pkg_ver}}. -->

## Statistical Endpoints

### Definition of a Positive Response

Positive responses were defined based on background-adjusted MFI values 
at the screening dilution level ([1:50]). 
Antigen-specific positivity thresholds were computed as the maximum of 100 or the 95th percentile 
of the baseline background-adjusted MFI minus background-adjusted blank (baseline net MFI) 
by antigen. 
Samples from post-enrollment visits were declared to have a positive binding 
antibody response by BAMA if they met three criteria:

>**A1.** Net MFI values at the screening dilution were greater than the maximum of 100 or 
the 95th percentile of baseline samples (by antigen).
**A2.** Net MFI values were greater than three times the baseline net MFI.
**A3.** Background-adjusted MFI values were greater than three times the baseline 
background-adjusted MFI values.

<!-- If you have differential binding antigens: -->
For antigens used to examine differential binding [to the VRC01 or CD4 binding site (CD4bs)], 
the following ratio-based positivity definition was used:

>**B1.** The 3-part response criteria (A1-A3) is positive for the experimental antigen.  
**B2.** The ratio of net MFI$_{\text{ experimental antigen}}$ to the net MFI$_{\text{ reference antigen}}$ 
(where either antigen net MFI was truncated to 100 when net MFI < 100), was greater than or equal to 2.5 
and net MFI$_{\text{ experimental antigen}}$ values were greater than or equal to 250.  
**B3.** The ratio of background-adjusted MFI$_{\text{ experimental antigen}}$ to the background-adjusted 
MFI$_{\text{ reference antigen}}$ (where either antigen background-adjusted MFI was truncated to 100 when 
background-adjusted MFI < 100), was greater than or equal to 2.5 and background-adjusted MFI$_{\text{ 
experimental antigen}}$ values were greater than or equal to 250.  
  

<!-- Either in an antigen summary table or in this section, include information 
on antigen-specific positivity thresholds. -->

### Response Magnitude

#### Net MFI

Log$_{10}$ background- and blank-subtracted MFI (net MFI) was used to evaluate
response magnitudes for each antigen and group. 
Values less than 1 were truncated at 1 before the log transformation was applied. 
Response magnitudes above 22,000 were considered saturated and were truncated 
at 22,000 for statistical analysis.

### AUTC

The area under the titration curve (AUTC) was calculated over the dilution series 
for each individual by visit and antigen using the trapezoidal integration with 
truncation at one in the case of negative net MFI values, or truncation at 22,000 
for net MFI values greater than 22,000.


#### Durability

<!-- if you have durability time points -->

To measure durability, the fold-change in response magnitude [net MFI or AUTC] 
between [week xx] (peak time point) and [week yy] (durability time point) 
was calculated. 
The fold-change was only calculated for antigens with data at both time points 
and for animals/participants with positive responses at peak, 
defined as: 
$\mathrm{log}{10}\text{(fold-change)} = \mathrm{log}{10}\mathrm{(X}{durability}{)} - \mathrm{log}{10}\mathrm{(X}{peak}{)}$, 
where X represents the response magnitude described above. 
For non-responders at durability with response magnitudes below the linear range 
of the assay (net MFI < 100), the value was set to $X{\text{durability}} = 100$ 
for plots and tables.

<!--if you have multiple durability time points--> 

Durability was also measured using area under the durability curve, 
starting with peak (week [xx]). 
Area under the curve (AUC) was estimated by animal/participant on the log$_{10}$ 
scale using the trapezoidal method. 
Net MFI values were truncated at 1 for AUC calculations.

### Differential Binding

<!-- Subtraction method. Using CD4bs as example. Do we want to remove antigen
specific references? open to suggestions on how to CD4 binding site -> epitope binding 
site? or just epitope specific region of the antigen? -->

Differential binding to the experimental antigen was defined as the difference in AUTC between 
binding to the experimental and reference antigens. A response was considered positive if it met 
the criterion for a positive response to the experimental antigen and satisfied the following 
additional condition:

4. $\Delta$AUTC $>$ 0, where $\Delta$AUTC was defined as $\mathrm{AUTC}_\mathrm{experimental}$ - $\mathrm{AUTC}_\mathrm{reference}$

Differential binding ratios were defined as the experimental antigen net MFI divided by the reference antigen net MFI. Differential 
binding ratios were computed as

$$ratio_w(\text{experimental, reference}) = \frac{\text{net MFI}_{\text{ experimental,} w}}{\text{net MFI}_{\text{ reference,} w}},$$ 
where net MFI$_{\text{ reference,} w}$ and net MFI$_{\text{ experimental,} w}$ refer to the net MFIs measured at Study Week $w$ for 
the reference and experimental antigens, respectively. In cases where the experimental or reference antigen net MFI were smaller than 
100, these values were set to 100 for ratio calculations.

#### Relative concentrations, relative concentration ratios, and percentages of epitope-specific antibodies

The relative concentration of vaccine-induced epitope-specific binding antibodies in each sample (i.e., participant and study visit) 
was estimated using a novel statistical method. This method integrated net MFI data across all available dilutions from all samples 
using a flexible statistical model. A spline function was built to describe the relationship between the log-transformed MFI measured 
by the BAMA assay and the relative concentration of binding antibodies in the samples. This spline function was specified as a quadratic 
B spline with monotone constraints. These constraints imposed the relationship between log-transformed MFI and relative concentrations 
to be monotone. The spline included a total of 12 equally spaced knots. The statistical model was fitted to the data using the Newton-Raphson 
procedure. It provided estimates of relative antibody concentrations (i.e., estimates of the unknown concentrations proportional to a common, 
unknown multiplicative factor shared by all samples). 

Ratios of antibody concentrations were deduced from ratios of these estimated relative concentrations. While both relative concentration 
ratios and differential binding ratios are designed to estimate antibody concentration ratios, discrepancies may arise between them, 
particularly when the net MFIs either saturate (>22,000) or fall below the limit of detection (<100). In such cases, interpreting the 
differential binding ratios becomes challenging. In contrast, ratios of relative concentrations are less sensitive to these issues because 
they integrate data across a range of dilutions. 

Percentage of epitope-specific antibodies were calculated based on the assumption that

$$ \text{Rel}\:\text{Conc}_{(epitope-specific)} = \text{Rel}\:\text{Conc}_{(antigen-specific)} - \text{Rel}\:\text{Conc}_{(epitope\:KO)} $$

where $\text{Rel}\:\text{Conc}_{(epitope-specific)}$ refers to the relative concentration of antigen-specific antibodies that bind to the 
epitope and $\text{Rel}\:\text{Conc}_{(antigen-specific)}$ and $\text{Rel}\:\text{Conc}_{(epitope\:KO)}$ refer to the relative concentration 
of vaccine-specific antibodies and the relative concentration of vaccine-specific antibodies binding to the mutated epitope KO immunogen, 
respectively (i.e., the relative concentrations of antibodies measured using experimental versus reference antigen). The estimated relative 
concentrations were therefore used to compute the percentage of epitope-specific antibodies as:
 
$$\text{Percent}_{(epitope-specific)} = \left(1-\frac{\text{Rel}\:\text{Conc}_{(epitope\:KO)}}{\text{Rel}\:\text{Conc}_{(antigen-specific)} }\right)\times 100\%\: $$ 

No response calls were performed based on the relative concentrations to identify samples with positive vaccine-induced binding antibody responses.

<!-- reference forthcoming -->

#### Avidity

BAMA avidity index (AI) is the ratio of the net MFI comparing two assay conditions:
using a citrate buffer wash (CIT), which disrupts lower-affinity antibody–antigen 
interactions, and a standard phosphate-buffered saline control (PBS). BAMA AI is 
defined as follows:

$$AI = 100 \times \frac{\text{Net MFI}_{\text{CIT}}}{\text{Net MFI}_{\text{PBS}}}$$

<!-- Specify whether AI was analyzed as continuous or as a categorical variable.
Note past analyses have used Low Net MFI when Net MFI was < 300, Low, Medium and High 
AI as categories. Be sure to consider in any statistical analysis the conditional 
nature of AI. AI is most likely not missing completely at random as it depends
on BAMA readouts. -->

#### AUC-MB

<!-- if you have all antigens from an ARP (antigen reagent project) panel -->

Individual-specific and group-averaged magnitude-breadth (MB) curves [@Huang2009-ao]
characterized the 
magnitude (binding antibody MFI\*) and 
breadth (number of antigens with positive response at a given value of net MFI that is greater than 100) 
of each individual plasma sample assayed against a panel of antigens. 
These curves were used to display the breadth of binding antibody activity in 
terms of the percentage of antigens with 
log$_{10}$ net MFI $>$ x for the range of $\mathrm{MFI}^{*}$ values, x. 
The antigen-specific net MFI value of each non-responder was set to 100.

The area under the MB curve (AUC-MB) was used to summarize the magnitude and 
breadth for each individual at a given time point across a set of antigens. 
$\mathrm{MFI}^{*}$ values were truncated at 100. 
The AUC-MB was calculated as the area under the MB-curves over the entire range 
without truncation, which is equivalent to the average of the log$_{10}$ net MFI 
over the panel of antigens.

<!-- If participants have filtered antigens in the panel, make sure to specify 
how missingness was handled. -->

## Exclusion Criteria

Samples were excluded if the blank MFI for the corresponding negative control 
was greater than 5,000. 
Records were excluded at all visits if any of the following occurred at baseline:

* Missing values for MFI, blank MFI, or net MFI
* High background, i.e., blank MFI for negative control > 5,000
* High baseline MFI or net MFI > 6,500

AUTC records were excluded if any of the dilutions were excluded.

## Graphical Analysis

Response rates were plotted, with accompanying Wilson score confidence intervals, 
for each experimental group, time point, and antigen.

Graphical distributions of response magnitudes [net MFI, AUTC, AUC-MB, etc] were 
plotted for each group and time point with box plots superimposed on the 
distribution of positive responders. The mid-line of the box denotes the median 
and the ends of the box denote the $25^{th}$ and $75^{th}$ percentiles. 
The whiskers denote the most extreme data points that were no more than 1.5 
times the interquartile range (i.e., height of the box). 
The magnitudes were plotted on a log$_{10}$ scale. AUTC and net MFI lower than 100 
were truncated to 100.

Distributions of durability (log$_{10}$ fold-change in response magnitude/durability AUC) 
were plotted for each group with superimposed box plots. 
Positive responders at [week xx] (peak) were included in the plot. 
The mid-line of the box denotes the median and the ends of the box denote the 
$25^{th}$ and $75^{th}$ percentiles. 
The whiskers denote the most extreme data points that were no more than 1.5 
times the interquartile range (i.e., height of the box). 
Response proportions were displayed for each group at week [xx, peak].

Individual-specific and group-average magnitude-breadth (MB) curves were plotted 
to display the breadth of binding antibody activities. 
[if applicable] MB curves were stratified by ARP panels (i.e., gp140, gp120 and V1V2).

Line plots were used to display the trend and the variability of the group
median net MFI or AUTC over time by antigen. 
Net MFI and AUTC values less than 100 were truncated at 100 for plotting purposes. 
Line plots were only displayed for antigens with at least one positive response 
at any time point.

## Statistical Tests

To assess if the treatment groups had different response rates than control, 
each group was compared to control using Barnard's exact test (two-sided, alpha = 0.05)
for each isotype and antigen [@Suissa1985; @Lyderson2009].
If there were any significant differences from control, 
pairwise treatment group tests were performed using Barnard's exact test
(two-sided, alpha = 0.05).

Pairwise comparisons of response magnitude ([AUTC, net MFI]) between study groups 
were performed using the Wilcoxon rank-sum test (two-sided, alpha = 0.05) on 
positive responders only. Tests between study groups required at least [three] 
positive responders in each treatment group.

Pairwise comparisons of net MFI durability (fold-change) between peak and 
durability were performed between treatment groups using the log-rank test 
(two-sided, alpha = 0.05) with Wilcoxon-Mann-Whitney scores and interval 
censoring for each antigen [@Fay2012].
The method outlined by @Fay2012 maintains the type I error rate under 
assessment-treatment dependence. 
A fold-change was considered censored when the net MFI value at the durability 
time point was below the linear range of the assay. 
For censored values, the lower bound of the interval was set to 
$\mathrm{log_{10}}$$\mathrm{(1/X_{\text{week [peak]}})}$ and 
the upper bound of the interval was set to 
$\mathrm{log_{10}}$$\mathrm{(100/X_{\text{week [peak]}})}$, 
where X represents net MFI, and 100 is the value of the lower bound of the linear 
range of the assay. 
Tests were only performed for pairs of groups where both groups had at least 3 
positive responders at peak, and the median fold-change for at least one group 
was observed (i.e., there were at least as many uncensored values as censored 
values for at least one group).

<!-- if you have multiple durability time points --> 
Comparisons of durability AUC (area under the response magnitude curve from 
peak, week [xx], through week [durability time point]) were made between
vaccine groups using the Wilcoxon rank-sum test (two-sided, alpha = 0.05). 
Durability AUC tests included responders and non-responders 
(with truncated net MFI measurements).

Corrections for multiple testing were not done for this analysis. 

<!-- OR -->

When several statistical comparisons were performed for the same endpoint (as is reported in a single
table), the p-values were adjusted for multiple testing by controlling the false discovery rate (FDR) using
the Benjamini-Hochberg procedure (@Benjamini:95). Adjusted p-values below 0.05 were
considered significant and highlighted as such in tables.
