---
title: "{{ study_name}} Lab Methods"
output: github_document
---

<!-- The markdown (*.md) file is generated from the R Markdown (*.Rmd) file.
Please edit the *.Rmd file. -->

<!-- this file was adapted from VISCtemplates {{pkg_ver}}. -->

Serum HIV-1 [IgG/IgA] responses against [# antigens] were measured on a Bio-Plex 
instrument (Bio-Rad) using a standardized custom HIV-1 Luminex assay 
[@tomaras2008].
The readout is background-subtracted median fluorescent intensity (MFI), 
where background refers to the antigen-specific plate-level control 
(i.e., a blank well containing antigen-conjugated beads run on each plate). 
The positive controls were [get this info from the lab]. 
Blank beads and blank wells (antigen-coupled beads + detection antibody) 
served as negative controls for non-specific binding. 
If the blank bead negative control exceeded 5,000 MFI, the sample was repeated. 
If the repeated value exceeded 5,000 MFI, the sample was excluded from analysis 
due to high background.

### BAMA Avidity

[Antigen and/or isotype specific] binding antibody responses were measured on a Bio-Plex 
(Bio-Rad) instrument (Bio-Plex 200 or Bio-Plex FM3D) using a standardized custom Luminex based assay.
Antigen specific antibody responses were measured at the following dilutions: [dilution (antigen/isotype) 
listed] and titrated [x-fold] [@tomaras2013].

Briefly, antigens were bound to carboxylated fluorescent microspheres (MagPlex, Luminex). Antigen bound 
microspheres were then incubated with human sera, along with standards and controls, for 30 minutes at 
750 RPM and 22°C. Mouse anti-human IgG1 (BioLegend, clone 12G8G11) and Mouse anti-human IgG3 (BioLegend, 
clone HP6047) followed by Goat Anti-Mouse IgG PE (Biolegend, catalog 405307) were used to detect IgG1 
and IgG3 antibody responses. Assay plates were read on the Bio-Plex 200 or Bio-Plex FM3D (Bio-Rad) 
system providing a readout of background subtracted mean fluorescence intensity (MFI).

All samples, controls and standards were assayed in duplicate; negative controls and uncoupled microspheres 
were included in each assay to ensure binding specificity. Positive and negative controls were included in 
each assay to ensure assay consistency and reproducibility. Levey-Jennings charts were also utilized to track 
antigen performance throughout the study.
