---
title: "Monolix Data Processing"
author: "Your Name"
date: "Created: YYYY-MM-DD, Last run: `r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(knitr.kable.NA = '-')

library(tidyverse)
library(glue)
library(here)
library(knitr)
library(kableExtra)
library(usethis)
```

## Install and check the data package

<!-- check against data specs: https://github.com/FredHutch/VISC-Assay-Methods/tree/master/PK/Assay_Data_Specs -->

```{r install-data-package, eval=FALSE}

remotes::install_git("N:/cavd/studies/cvdxxx/pdata/xxx.git")
```

```{r load-data-package}

# Load PK concentrations and assign to pk_data 
library(Ho785)
data("Ho785_covance_elisa_pk")

pk_data <- Ho785_covance_elisa_pk

glimpse(pk_data)
```

<!-- The STP should create a table of missing concentrations in the QC report. You may want to further investigate patterns of missingness here. -->

```{r check-for-missing-concentrations}

# this will only work if there is one row per expected visit in the data package
pk_data %>% 
  filter(is.na(concentration)) %>% 
  group_by(pubid) %>% 
  summarise(
    missing_visits = paste0(visit_type, collapse = ", ")
  ) %>% 
  kable() %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<!-- Next, check dose and covariate data. -->

```{r check-dose}

# these variables are used to calculate AMT
pk_data %>% 
  distinct(group, analyte, route, dose, dose_units) %>% 
  arrange(group, analyte) %>% 
  kable() %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

```{r check-units}

# check other units that are used for calculating covariate values

pk_data %>% distinct(weight_unit, height_unit)
```

<!-- Usually, we evaluate participant weight, BMI, age, sex as covariates in the PK model. Baseline serum albumin is another covariate worth investigating. Bajaj et. al (2019) found that baseline body weight, serum albumin, and sex are the most commonly identified covariates in oncology PK models (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6710515/).  -->

<!-- At pre-infusion time points, concentrations of the analyte should be LLoQ. If not, plot these data and have a discussion about how you will take it into account in the PK model. -->

```{r check-pre-infusion}

# check for concentrations > LLOQ at pre-infusion time points
pk_data %>% 
  filter(visit_type == "1.00 A") %>% 
  filter(concentration > lloq) %>% 
  select(pubid, arm, group, concentration, concentration_units) %>% 
  kable() %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

## Format data for Monolix/PKanalix

<!-- 

The next step is to create the CSV files for use with Monolix or PKanalix. 

Data specs for these CSV files: https://github.com/FredHutch/VISC-Assay-Methods/blob/master/PK/Assay_Data_Specs/Monolix_data.md 

-->

<!-- You will need to filter out the placebo participants. You can do this by using the unblinding variable if it is available. If you don't have the unblinding variable, you can filter out participants who have all concentrations <= LLOQ. -->

```{r pre-process-data}

# calculate any variables that you need and are not in the data package
cvdxxx_elisa_preprocess <- pk_data %>%
  filter(analyte != "Placebo") %>% 
  mutate(
    dose_amount = dose*weight,
    bmi = weight/((height/100)**2),
    censored = if_else(concentration_ug <= lloq_ug, 1, 0),
    ) %>% 
  select(
    pubid, analyte, group, hiv_status, route, dose, dose_units, dose_amount,
    infusion_no, infusion_dur,
    visitno, day, study_day, concentration, lloq, censored,
    sex, age, weight, height, bmi
    ) 

# export data 
usethis::use_data(cvdxxx_elisa_preprocess, overwrite = TRUE)
```

<!-- Now create the datasets that will be exported to CSVs for Monolix. If you don't have a row for the infusion time point in the data (day == 0), you will need to add that in. -->

```{r monolix-data}

# Monolix uses "." to designate missing values
# For each participant, the first row should be day == 0 with the dose amount (AMT). The concentration (DV) is "." at this time point.

monolix_data <- cvdxxx_elisa_preprocess %>% 
  filter(day >= 0) %>% # we don't use pre-infusion time points in the PK analysis
  group_by(pubid, infusion_no) %>% 
  mutate(
    AMT = if_else(day == 0, dose_amount, 0),
    ADM = case_when(
      AMT != 0 & route == "SC" ~ "2",
      AMT != 0 & route == "IV" ~ "1",
      TRUE ~ "."
    ),
    RATE = if_else(ADM == "1", as.character(AMT/infusion_dur), ".")
  ) %>% 
  select(
    ID = pubid, ANALYTE = analyte,
    TIME = day, DV = concentration, AMT, ADM, RATE, CENS, LLOQ = lloq,
    WT = weight, HT = height, BMI = bmi, SEX = sex, AGE = age, 
    GROUP = group,  ROUTE = route, HIVSTATUS = hiv_status,
    DATAVERSION = DataPackageR::data_version("Ho785") # good idea to add as a column as a check that you have the right data version installed
  ) %>% 
  arrange(ID, TIME)
```

## Write CSV files

### For all participants

```{r write-csv}
csv_path <- here("inst", "extdata", "elisa")

monolix_data %>% write_csv(here(csv_path, "elisapk_all_pubids.csv"), na = ".")
```

### Subset of participants

<!-- Write a function to subset the data by group, route, etc. -->

```{r}

groups <- unique(monolix_data$GROUP)
routes <- unique(monolix_data$ROUTE)

write_csv_by_var <- function(var_type, var_name, var_value) {
  
  monolix_data %>% 
    filter_at(vars({{var_name}}), ~ .x == var_value) %>% 
    write_csv(here(csv_path, glue("elisapk_{var_type}_{var_value}.csv")), na = ".")
}

map(groups, ~write_csv_by_var("group", GROUP, .))
map(routes, ~write_csv_by_var("route", ROUTE, .))
```
