---
title: "icaba-lab-methods"
output: html_document
date: '2022-10-31'
---

# Lab Methods

The measurement of plasma Ab binding to HIV-1 envelope expressed on the surface of infected cells is conducted using flow-cytometry-based indirect surface staining according to methods similar to those previously described (@pmid21543485; @pmid28593989). Briefly, mock infected and HIV-1 BG505 Infectious Molecular Clones-infected CEM.NKRCCR5 cells were incubated with 1:100[adjust if using different dilutions] dilutions of plasma samples of interest for 2h at 37°C, then stained with a vital dye (Live/Dead Aqua) to exclude dead cells from analysis. The cells were subsequently washed, and permeabilized using BD Cytofix/Cytoperm solution. After an additional wash, cells were stained with FITC-conjugated goat-anti-Rhesus IgG polyclonal antisera to detect binding of the plasma Ab, and PE-conjugated anti-HIV-1 p24 Ab (RD1) to identify infected cells. Cells positive for binding NHP plasma Ab were defined as live, p24 positive, and FITC positive. Final results were reported as percent of FITC positive cells and FITC MFI among the viable p24 positive events after subtracting the background observed for the prevaccination samples.


