---
title: "statistical-methods"
output: html_document
date: '2022-10-27'
---

<!-- This file was adapted from VISCtemplates {{pkg_ver}}. -->

# Statistical Methods

## Graphical analysis

Response rates were plotted for each antigen at each time point. Response rates were also plotted on radar plots, which depicted the response rate for each antigen as a point on an individual spoke. 

Distributions of peak and AUTC across time were plotted for each antigen with box plots superimposed on the distribution of responders. The mid-line of the box denoted the median and the ends of the box denoted the $25^{th}$ and $75^{th}$ percentiles. The whiskers denoted the most extreme data points that were no more than 1.5 times the interquartile range (i.e., height of the box). Lines connected each participant at each time point.

Individual sample-specific magnitude-breadth (MB) curve curves were plotted where the x-axis represented a response magnitude value (x) and the y-axis represented the fraction of antigens or isolates with response magnitudes less than x. In addition to the individual sample-specific curves, the group-specific curve displayed the average MB across all subjects in that group. 

Distributions of durability (area under the durability curve) were plotted with superimposed box plots. The mid-line of the box denoted the median and the ends of the box denoted the $25^{th}$ and $75^{th}$ percentiles. The whiskers denoted the most extreme data points that were no more than 1.5 times the interquartile range (i.e., height of the box).


## Statistical tests

Response rates and magnitudes were summarized by timepoints. Pairwise comparisons of response rates between groups at each timepoint was conducted using Barnard's exact test (two-sided, alpha = 0.05) (@Lyderson2009; @Suissa1985). Pairwise comparisons of response magnitudes between groups at each timepoint was conducted using the Wilcoxon rank-sum test (two-sided, alpha = 0.05) among positive responders. 

Within each treatment group, response rates and response magnitudes between the timepoints were compared using the McNemar's Test and Wilcoxon signed-rank test respectively (two-sided, alpha = 0.05).  

Response magnitude tests required at least four positive responders in at least one of the treatment groups being compared. If at least four responders were detected among all dose levels, global tests for response magnitude would be performed using the Kruskal-Wallis test (approximate distribution, alpha = 0.05) (@Hothorn2008). If the global test was significant, then the pairwise dose group comparisons would be performed among the treatment groups. Censored measurements below the assay quantification limit were treated as ties with ties handled using the Wilcoxon rank-sum exact method. Durability, as defined by change in response magnitude, was measured using area under the AUTC curve from peak to the final durability time point ([insert final time point, e.g., week 48]). 
