---
title: "lab-methods"
output: html_document
date: '2022-10-26'
---

<!-- This file was adapted from VISCtemplates {{pkg_ver}}. -->


# Lab Methods
ADCC-mediated antibody responses were measured by ADCC GranToxiLux (GTL) [@Pollara2011] and tested against [insert antigens]. Participant sera were incubated with effector cells and gp120-coated target cells and ADCC was quantified as net percent granzyme B activity, which is the percent of target cells positive for GranToxiLux (GTL) detected by flow cytometry. For each subject at each timepoint, percent granzyme B activity was measured at [#] dilution levels: [insert dilution levels] for each antigen. The analyses in the data focused on the readouts indicated in the statistical methods. Peak activity less than 0\% was set to 0\%. A positive response was defined as peak activity greater than or equal to 8%. 

The monoclonal antibody Synagis and a cocktail of HIV-1 monoclonal Abs (A32, 2G12, CH44, and 7B2) were used as negative and positive controls, respectively.
